# Generated by Django 4.0.8 on 2022-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(max_length=64),
        ),
    ]
